# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  # ชื่อของ Jobs
  build:
    docker:
      # specify the version
      # base image
      - image: circleci/golang:1.9

    working_directory: /go/src/app
    # มีกี่ step ก็ได้
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go mod download
      - run: go build -o ./main ./main.go
      - run: echo done!