# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  # ชื่อของ Jobs
  build:
    docker:
      # specify the version
      # base image
      - image: golang:1.13.3-alpine

    working_directory: /go/src/app
    # มีกี่ step ก็ได้
    steps:
      - checkout
      - run: go mod download
      - run: go build -o ./main ./main.go
      - run: echo done!
      # deploy dockerhub
      - setup_remote_docker
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: "Build docker image and push to docker hub"
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              cp Dockerfile.production Dockerfile
              docker build -t paretk/example-go-circle:latest .
              docker build -t paretk/example-go-circle:${CIRCLE_SHA1} .
              docker push paretk/example-go-circle:latest
              docker push paretk/example-go-circle:${CIRCLE_SHA1}
            elif [ "${CIRCLE_BRANCH}" == "staging" ]; then
              docker build -t paretk/example-go-circle-staging:latest .
              docker push paretk/example-go-circle-staging:latest
            else
              echo "This is ${CIRCLE_BRANCH}"
            fi
      - run: echo build-docker done!
