# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  # ชื่อของ Jobs
  build:
    docker:
      # specify the version
      # base image
      - image: circleci/golang:1.13.3-stretch

    working_directory: /go/src/app
    # มีกี่ step ก็ได้
    steps:
      - checkout
      - run: go mod download
      - run: go build -o ./main ./main.go
      - run: echo done!
      # deploy dockerhub
      - setup_remote_docker
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: "Build docker image and push to docker hub"
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker build -t paretk/example-go-circle:latest .
              docker build -t paretk/example-go-circle:${CIRCLE_SHA1} .
              docker push paretk/example-go-circle:latest
              docker push paretk/example-go-circle:${CIRCLE_SHA1}
            elif [ "${CIRCLE_BRANCH}" == "staging" ]; then
              docker build -t paretk/example-go-circle-staging:latest .
              docker push paretk/example-go-circle-staging:latest
            else
              echo "This is ${CIRCLE_BRANCH}"
            fi
      - run: echo build-docker done!
      - run:
          name: "Trigger rancher upgrade"
          # batch_size upgrade ทีละ 3 container (1 ใน 2 ของ container ทั้งหมด)
          # start_first กิน resource ก่อนเลยถ้า deploy ได้ก็จะปิดเครื่องเก่า
          # auto_complete ไม่ต้องกด upgrade เอง
          command: |
            docker run --rm -it \
              -e CATTLE_ACCESS_KEY="$CATTLE_ACCESS_KEY" \
              -e CATTLE_SECRET_KEY="$CATTLE_SECRET_KEY" \
              -e CATTLE_URL="$CATTLE_URL" \
              etlweather/gaucho upgrade $RANCHER_SERVICE \
              --imageUuid 'docker:paretk/example-go-circle:latest' \
              --batch_size 3 --start_first \
              --auto_complete --timeout 600 \
              /
      - run: echo build-docker done!
