# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  # ชื่อของ Jobs
  build:
    docker:
      # specify the version
      # base image
      - image: golang:1.13.3-alpine

    working_directory: /go/src/app
    # มีกี่ step ก็ได้
    steps:
      - checkout
      - run: go mod download
      - run: go build -o ./main ./main.go
      - run: echo done!